### PR TITLE
Minor doc tweaks so they compile straight away

### PR DESCRIPTION
**Pull request by michael-grunder**
Just small changes to README.md so the examples compile outside of the crate.

### CODE REVIEW

**Comment by rmanoka** [comment]
@michael-grunder Thanks for the contributions!

Are you sure `#![feature(async_closure)]` is necessary to compile?  I don't use it elsewhere in the code, and the tests seem to succeed without it.  This feature is [still unstable](https://github.com/rust-lang/rust/issues/62290), and we should avoid unless necessary.

**Comment by michael-grunder** [comment]
Thanks for the reply!

I pulled the code out into a separate project and switched them to normal async functions (as opposed to tests).

Looks like [scoped_futures](https://github.com/michael-grunder/use-async-scoped/blob/6ed65b90a0ad97d29319cdc2d2761f44173a6c42/src/main.rs#L5) does need the directive, while [test_scope_and_block](https://github.com/michael-grunder/use-async-scoped/blob/6ed65b90a0ad97d29319cdc2d2761f44173a6c42/src/main.rs#L20) does not.

I'm not sure on why though, since it sure _looks_ like they're both using async closures, but I'm still pretty new to Rust (and especially async rust).

You can find the repo [here](https://github.com/michael-grunder/use-async-scoped).

**Comment by rmanoka** [comment]
Oh right!  We should swap the order: use `|| async` instead of `async ||`.  The former is just a regular closure that returns a future and the latter is an async_closure.  Could you make that change and remove the feature attributes?

Thanks!

**Comment by rmanoka** [comment]
Looks good to me. Thanks!

**Pull request merged**
